### ISSUE TITLE
Question on toggle

### ISSUE THREAD

**Issue by KLucky13** [onfoot/homebridge-shelly-shutter#11]
Hi,

I have ordered a shelly 2.5 and tube motor. I came across your script and I was wondering how the "toggle" exactly works. I ordered 2 mechanical push buttons from aliexpress to act as physical switches (1 for up and another one for down). Do I understand correctly that the "toggle" feature reacts on the physical switches and I only need one in this case? Or how does it work?

Thanks,

Kenny

**Comment by onfoot** [comment]
Hi, congrats on the purchase! ;)

The toggle function here shows up as a Switch in Home app (because it's a homebridge plugin), so that when you turn it on, the shutter starts moving in the opposite direction of the last movement. When turned off, shutter stops.

It has nothing to do with any physical buttons you connect to Shelly whatsoever.

**Comment by KLucky13** [comment]
Allright thanks, so I did understand it wrong :-) Ok so I'll stick to 2 switches. The functionality I described would be neat however, but that would go down to the firmware of the shelly I assume. I'm new to shelly 2.5 so I'll be learning it this weekend when I install everything :-) Are you running the stock shelly firmware? I read that there are firmwares available to add the shelly straight to homekit as well.

**Comment by onfoot** [comment]
Yep, I'm rocking the stock firmware, since I have a lot of non-homekit devices, so hacking Shellies wouldn't make too much of a difference. And as a bonus I get some additional features thanks to my plugin (like roller touch-down point and soon a more precise center-point configuration).
